apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ${CATALOG_SOURCE_NAME} #rename to qe-app-registry
  namespace: openshift-marketplace
spec:
  displayName: NetObservUnreleasedTesting
  image: ${IMAGE}
  sourceType: grpc
